# Generated by Django 4.0.4 on 2022-05-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='ocupación',
            new_name='ocupacion',
        ),
    ]
